### ISSUE TITLE
token_id_not_found or Requested authority could not be found

### ISSUE THREAD

**Issue by fjlogrono** [Azure-Samples/active-directory-verifiable-credentials-dotnet#20]
- [x] bug report

### Minimal steps to reproduce

Download the sample (https://github.com/Azure-Samples/active-directory-verifiable-credentials-dotnet.git)
Follow all instructions to setup, including creating the credentials, creating the application in AD, setting up the service principal, granting appropriate permissions as per instructions
Render site (using ngrok)
Generate qrCode with PIN successfully
Attempt to add credential to Authenticator wallet.
See error at Authenticator "Sorry, you can't go any further..."

### Any log messages given by the failure
The first time I scan the code:
{"requestId":"44b2896dd8252de28853e35d6855a129","date":"Wed, 15 Jun 2022 09:44:57 GMT","mscv":"61u3wfBNQVCAe6jUETLECQ.1.0","error":{"code":"authorityNotFound","message":"Requested authority could not be found"}}

The following times I scan the code:
{"requestId":"e16b2d6ea088f2afea7dd5a00579027d","date":"Wed, 15 Jun 2022 09:27:31 GMT","mscv":"/+ALQqo0SOeLtRNswjz84g.1.0","error":{"code":"client_request.token_id_not_found","message":"Requested 'dd0d807a-7e23-4ef1-8295-3c16d049bff7' not found."}}

### Expected/desired behavior

Have authenticator view the credential that was issued

### OS and Version?
> Windows 11

### Versions

Authenticator v 6.5.85

### Mention any other details that might be useful
com.microsoft.did.sdk.util.controlflow.NotFoundException: {"requestId":"cc21ab5fa1629e154aefb713d213da2d","date":"Wed, 15 Jun 2022 09:26:58 GMT","mscv":"tWF6o1FHRjSnwffBGJgKdQ.1.0","error":{"code":"authorityNotFound","message":"Requested authority could not be found"}}
	at com.microsoft.did.sdk.datasource.network.BaseNetworkOperation.onFailure(BaseNetworkOperation.kt:66)
	at com.microsoft.did.sdk.datasource.network.BaseNetworkOperation.fire$suspendImpl(BaseNetworkOperation.kt:44)
	at com.microsoft.did.sdk.datasource.network.BaseNetworkOperation$fire$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:75)
	at androidx.lifecycle.DispatchQueue.enqueue(DispatchQueue.kt:112)
	at androidx.lifecycle.DispatchQueue.access$enqueue(DispatchQueue.kt:31)
	at androidx.lifecycle.DispatchQueue$dispatchAndEnqueue$$inlined$with$lambda$1.run(DispatchQueue.kt:100)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7403)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
 [main]
2022-06-15 09:27:31,438 INFO/DID_SDK/: HttpError: 404 body: {"requestId":"e16b2d6ea088f2afea7dd5a00579027d","date":"Wed, 15 Jun 2022 09:27:31 GMT","mscv":"/+ALQqo0SOeLtRNswjz84g.1.0","error":{"code":"client_request.token_id_not_found","message":"Requested 'dd0d807a-7e23-4ef1-8295-3c16d049bff7' not found."}} cv: /+ALQqo0SOeLtRNswjz84g.1.0 [main]
2022-06-15 09:27:31,439 INFO/DID_SDK/: com.microsoft.did.sdk.util.controlflow.NotFoundException: {"requestId":"e16b2d6ea088f2afea7dd5a00579027d","date":"Wed, 15 Jun 2022 09:27:31 GMT","mscv":"/+ALQqo0SOeLtRNswjz84g.1.0","error":{"code":"client_request.token_id_not_found","message":"Requested 'dd0d807a-7e23-4ef1-8295-3c16d049bff7' not found."}}
	at com.microsoft.did.sdk.datasource.network.BaseNetworkOperation.onFailure(BaseNetworkOperation.kt:66)
	at com.microsoft.did.sdk.datasource.network.BaseNetworkOperation.fire$suspendImpl(BaseNetworkOperation.kt:44)
	at com.microsoft.did.sdk.datasource.

**Comment by fjlogrono** [comment]
The problem was the Endpoint, in my was must be https://beta.eu.did.msidentity.com/v1.0/{0}/verifiablecredentials/request
